---
- name: Install software using play scope variable
  hosts: all
  vars:
   - a: tomcat8
   - b: present
   - c: yes
  tasks:
   - name: Install tomcat8
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
