---
- name: Install/uninstall/upgrade software using loops by changing multiple variables
  hosts: all
  tasks:
   - name: Install/uninstall/upgrade software 
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: yes}
      - {a: git,b: absent,c: no}
      - {a: maven,b: latest,c: yes}
...
