---
- name: Configuring tomcat8
  hosts: all
  tasks:
   - name: Install tomcat8
     apt:
      name: tomcat8
      state: present
      update_cache: yes
   - name: Install tomcat8-admin
     apt:
      name: tomcat8-admin
      state: present
      update_cache: yes
   - name: Copy tomcat-users.xml into /etc/tomcat8 folder
     copy:
      src: /home/ubuntu/tomcat-users.xml
      dest: /etc/tomcat8
   - name: change tomcat port from 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat8/server.xml
   - name: change tomcat port from 9090 to 8080
     replace:
      regexp: 9090
      replace: 8080
      path: /etc/tomcat8/server.xml
   - name: Restart tomcat8
     service:
      name: tomcat8
      state: restarted
   - name: Pause playbook for sometime
     pause:
      seconds: 2
   - name: Check url response of server1
     uri: 
      url: http://172.31.5.113:8080
      status_code: 200
   - name: Check url response of server2
     uri:
      url: http://172.31.5.239:8080
      status_code: 200
...
