---
- name: configuring apache2
  hosts: all
  become: yes
  tasks:
  - name: Install apache2
    apt:
     name: apache2
     state: present
     update_cache: yes
  - name: Edit the file index.html
    copy:
     content: "Welcome to my place"
     dest: /var/www/html/index.html
  - name: Restart apache2
    service:
     name: apache2
     state: restarted
  - name: Check url response of server1
    uri:
     url: http://172.31.5.113
     status_code: 200
  - name: Check url response of server2
    uri:
     url: http://172.31.5.239
     status_code: 200   
...
