---
- name: create a user on all the managed nodes
  hosts: all
  tasks:
   - name: create a user
     user:
      name: Sai
      password: sai
      uid: 1357
      home: /home/Sai
      comment: "A normal user"
      shell: /bin/bash
...
