---
- name: Implementing when conditions
  hosts: all
  vars:
   - a: 20
  tasks:
   - name: create file based on a condition
     file:
      name: /tmp/file56
      state: touch
     when: a == 20
...
