---
- name: create a user and copy /etc/passwd file into user's home directory
  hosts: all
  tasks:
   - name: create a user
     user:
      name: Anu
      password: anu
      home: /home/Anu
   - name: copy /etc/passwd file into user's home directory
     copy:
      src: /etc/passwd
      dest: /home/Anu
...
